// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProjectManager.Data;
using ProjectManager.Models.ConstAndEnums;
using ProjectManager.Models.ProductKnowledge;
using System;

namespace ProjectManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ProjectManager.Areas.Waterfall.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SourceTaskId");

                    b.Property<int>("TargetTaskId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("GanttLinks");
                });

            modelBuilder.Entity("ProjectManager.Areas.Waterfall.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Duration");

                    b.Property<int?>("ParentId");

                    b.Property<decimal>("Progress");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Text");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("GanttTasks");
                });

            modelBuilder.Entity("ProjectManager.Models.AdditionalFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("AdditionalFiles");
                });

            modelBuilder.Entity("ProjectManager.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<int?>("LastSelectedProjectId");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ProjectManager.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AutorId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("OwnerId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ProjectManager.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ProjectManager.Models.CustomerWish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddingTime");

                    b.Property<int?>("AdditionalFilesId");

                    b.Property<int?>("AutorId");

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalFilesId");

                    b.HasIndex("AutorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("CustomerWishes");
                });

            modelBuilder.Entity("ProjectManager.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivitiesId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("ActivitiesId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ProjectManager.Models.FilePath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OwnerId");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("FilePaths");
                });

            modelBuilder.Entity("ProjectManager.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DepartmentId");

                    b.Property<int?>("ProjectId");

                    b.Property<int>("Role");

                    b.Property<double>("Salary");

                    b.Property<int?>("TeamId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("ProjectManager.Models.ProductKnowledge.Expression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("LeftVariableId");

                    b.Property<int>("Ratio");

                    b.Property<string>("RightVariable");

                    b.Property<int?>("RuleId");

                    b.HasKey("Id");

                    b.HasIndex("LeftVariableId");

                    b.HasIndex("RuleId");

                    b.ToTable("Expression");
                });

            modelBuilder.Entity("ProjectManager.Models.ProductKnowledge.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Result");

                    b.Property<int?>("RightVariableId");

                    b.HasKey("Id");

                    b.HasIndex("RightVariableId");

                    b.ToTable("ProductKnowledgeRules");
                });

            modelBuilder.Entity("ProjectManager.Models.ProductKnowledge.Variable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("ProductKnowledgeVariables");
                });

            modelBuilder.Entity("ProjectManager.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivitiesId");

                    b.Property<double>("Budget");

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<int>("ProjectType");

                    b.HasKey("Id");

                    b.HasIndex("ActivitiesId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectManager.Models.ProjectActivities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ProjectActivities");
                });

            modelBuilder.Entity("ProjectManager.Models.ProjectActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("InitializerId");

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectActivitiesId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("InitializerId");

                    b.HasIndex("ProjectActivitiesId");

                    b.ToTable("ProjectActivity");
                });

            modelBuilder.Entity("ProjectManager.Models.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivitiesId");

                    b.Property<DateTime>("AddingTime");

                    b.Property<int?>("AdditionalFilesId");

                    b.Property<int?>("AssigneeId");

                    b.Property<int?>("BaseTaskId");

                    b.Property<int?>("CommentsId");

                    b.Property<int>("ComplitedLine");

                    b.Property<DateTime>("Deadline");

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Description");

                    b.Property<DateTime>("FinishedTime");

                    b.Property<TimeSpan>("MaxEstimate");

                    b.Property<TimeSpan>("MinEstimate");

                    b.Property<string>("Name");

                    b.Property<int>("Priority");

                    b.Property<int?>("ProjectId");

                    b.Property<int?>("SprintId");

                    b.Property<int>("Status");

                    b.Property<int?>("TeamId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ActivitiesId");

                    b.HasIndex("AdditionalFilesId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("BaseTaskId");

                    b.HasIndex("CommentsId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SprintId");

                    b.HasIndex("TeamId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ProjectManager.Models.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<int>("Duration");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsFinished");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartTime");

                    b.Property<int?>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("ProjectManager.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivitiesId");

                    b.Property<int?>("DepartmentId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ActivitiesId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ProjectManager.Models.WorkPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("End");

                    b.Property<bool>("Finished");

                    b.Property<int?>("ParticipantId");

                    b.Property<DateTime>("Start");

                    b.Property<int?>("TaskId");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkPeriod");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectManager.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectManager.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectManager.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectManager.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectManager.Models.Comment", b =>
                {
                    b.HasOne("ProjectManager.Models.Participant", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId");

                    b.HasOne("ProjectManager.Models.Comments", "Owner")
                        .WithMany("List")
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("ProjectManager.Models.CustomerWish", b =>
                {
                    b.HasOne("ProjectManager.Models.AdditionalFiles", "AdditionalFiles")
                        .WithMany()
                        .HasForeignKey("AdditionalFilesId");

                    b.HasOne("ProjectManager.Models.Participant", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId");

                    b.HasOne("ProjectManager.Models.Project", "Project")
                        .WithMany("CustomerWishes")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("ProjectManager.Models.Department", b =>
                {
                    b.HasOne("ProjectManager.Models.ProjectActivities", "Activities")
                        .WithMany()
                        .HasForeignKey("ActivitiesId");

                    b.HasOne("ProjectManager.Models.Project", "Project")
                        .WithMany("Departments")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("ProjectManager.Models.FilePath", b =>
                {
                    b.HasOne("ProjectManager.Models.AdditionalFiles", "Owner")
                        .WithMany("Files")
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("ProjectManager.Models.Participant", b =>
                {
                    b.HasOne("ProjectManager.Models.Department", "Department")
                        .WithMany("Participants")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ProjectManager.Models.Project", "Project")
                        .WithMany("Participants")
                        .HasForeignKey("ProjectId");

                    b.HasOne("ProjectManager.Models.Team", "Team")
                        .WithMany("Participants")
                        .HasForeignKey("TeamId");

                    b.HasOne("ProjectManager.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ProjectManager.Models.ProductKnowledge.Expression", b =>
                {
                    b.HasOne("ProjectManager.Models.ProductKnowledge.Variable", "LeftVariable")
                        .WithMany()
                        .HasForeignKey("LeftVariableId");

                    b.HasOne("ProjectManager.Models.ProductKnowledge.Rule")
                        .WithMany("Expressions")
                        .HasForeignKey("RuleId");
                });

            modelBuilder.Entity("ProjectManager.Models.ProductKnowledge.Rule", b =>
                {
                    b.HasOne("ProjectManager.Models.ProductKnowledge.Variable", "RightVariable")
                        .WithMany()
                        .HasForeignKey("RightVariableId");
                });

            modelBuilder.Entity("ProjectManager.Models.Project", b =>
                {
                    b.HasOne("ProjectManager.Models.ProjectActivities", "Activities")
                        .WithMany()
                        .HasForeignKey("ActivitiesId");
                });

            modelBuilder.Entity("ProjectManager.Models.ProjectActivity", b =>
                {
                    b.HasOne("ProjectManager.Models.Participant", "Initializer")
                        .WithMany()
                        .HasForeignKey("InitializerId");

                    b.HasOne("ProjectManager.Models.ProjectActivities")
                        .WithMany("List")
                        .HasForeignKey("ProjectActivitiesId");
                });

            modelBuilder.Entity("ProjectManager.Models.ProjectTask", b =>
                {
                    b.HasOne("ProjectManager.Models.ProjectActivities", "Activities")
                        .WithMany()
                        .HasForeignKey("ActivitiesId");

                    b.HasOne("ProjectManager.Models.AdditionalFiles", "AdditionalFiles")
                        .WithMany()
                        .HasForeignKey("AdditionalFilesId");

                    b.HasOne("ProjectManager.Models.Participant", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("ProjectManager.Models.ProjectTask", "BaseTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("BaseTaskId");

                    b.HasOne("ProjectManager.Models.Comments", "Comments")
                        .WithMany()
                        .HasForeignKey("CommentsId");

                    b.HasOne("ProjectManager.Models.Department", "Department")
                        .WithMany("Tasks")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ProjectManager.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId");

                    b.HasOne("ProjectManager.Models.Sprint", "Sprint")
                        .WithMany("ListTasks")
                        .HasForeignKey("SprintId");

                    b.HasOne("ProjectManager.Models.Team", "Team")
                        .WithMany("Tasks")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("ProjectManager.Models.Sprint", b =>
                {
                    b.HasOne("ProjectManager.Models.Team", "Team")
                        .WithMany("Sprints")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("ProjectManager.Models.Team", b =>
                {
                    b.HasOne("ProjectManager.Models.ProjectActivities", "Activities")
                        .WithMany()
                        .HasForeignKey("ActivitiesId");

                    b.HasOne("ProjectManager.Models.Department", "Department")
                        .WithMany("Teams")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("ProjectManager.Models.WorkPeriod", b =>
                {
                    b.HasOne("ProjectManager.Models.Participant", "Participant")
                        .WithMany("WorkPeriods")
                        .HasForeignKey("ParticipantId");

                    b.HasOne("ProjectManager.Models.ProjectTask", "Task")
                        .WithMany("WorkPeriods")
                        .HasForeignKey("TaskId");
                });
#pragma warning restore 612, 618
        }
    }
}
